version: "3.2"

services:
  wikidump:
    build: .
    restart: always
    ports:
      - 80:80
      - 5000:5000
    volumes:
      - ./app/:/app/
      - ./var/log/:/var/log/
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./default:/etc/nginx/sites-available/default
      - ./uwsgi.ini:/etc/uwsgi/uwsgi.ini
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./var/log/nginx/:/var/log/nginx/
      - ./var/log/uwsgi/:/var/log/uwsgi/
      - ./var/log/app/:/var/log/app/
      - ./var/log/supervisor/:/var/log/supervisor/
